### PR TITLE
Fix MPI linking issue

### PR DESCRIPTION
**Pull request by ryanmrichard**

### CODE REVIEW

**Comment by ryanmrichard** [comment]
Did that fix it?

**Comment by keipertk** [comment]
I don't think I can point to the PR branch w/o changing the groovy script in developertools. So I haven't tested.

**Comment by ryanmrichard** [comment]
I thought you said you saw the issue before? Was it not local?

**Comment by keipertk** [comment]
I saw the issue yesterday on Jenkins. I was (blindly) hoping that your changes to CPP last night would fix it, but still seeing the issue this morning.

**Comment by keipertk** [comment]
I forgot about your Jenkins replay magic...nice

**Pull request merged**
